### PR TITLE
Merge upstream changes

### PR DESCRIPTION
**Pull request by ljbade**
Our fork of prometheus-cpp is fairly out of date and I want to use some of the fixes and improvements from upstream.

### CODE REVIEW

**Comment by ljbade** [comment]
@jbangelo I wasn't 100% sure who should review this PR. I guess this repo is owned by the Orion team?

**Comment by jbangelo** [comment]
I don't think we can reasonably review all of the upstream changes. @ljbade were there any conflicts that we should focus on? All I can see is commit d3847e514bd82b59f537c60a413b382552793f79.

Something else to consider, would it be cleaner to try and rebase our changes on top of the upstream master rather than merging in the upstream master. We'll end up in the same place, but it would make it a little more clear that we are simply adding a handful of modifications on top of the upstream rather than a massively divergent fork.

**Comment by ljbade** [comment]
@jbangelo yeah that might be an easier way to do this. There were a lot of merge conflicts because some of the code has been moved around.

**Comment by ljbade** [comment]
Replaced by https://github.com/swift-nav/prometheus-cpp/pull/7

**Pull request closed without merging**
