### PR TITLE
Rebase upstream changes

### PR DESCRIPTION
**Pull request by ljbade**
Our fork of prometheus-cpp is fairly out of date and I want to use some of the fixes and improvements from upstream.

I also fixed an unused variable error that shows up under latest upstream CI pipeline in the expired metrics code.

Finally I also fixed up bunch of missing/incorrect headers that show up with include-what-you-use which upstream enforces.

As for what to review, basically only the last three commits that are different from upstream:
- Add support for expiring metrics
- Run IWYU and fix most issues
- Fix missing std:: on size_t
- Fix reference alignment formatting

### CODE REVIEW

**Comment by ljbade** [comment]
I removed the commit "Override labels with constant labels." because it turns out upstream has already fixed this issue on duplicate labels here - https://github.com/jupp0r/prometheus-cpp/blob/master/core/src/family.cc#L50

**Comment by ljbade** [comment]
I had an annoying issue with the other PRs where clang-format wasn't correctly putting the `&` symbols aligned left on variable definitions. Was ending up with mix of left aligned (what everything in the project uses), and right aligned which is what we use in our own code. So set the clang-format file to avoid this.

**Comment by silverjam** [comment]
>   * Add support for expiring metrics

Have we tried to upstream this feature?  This seems pretty self-contained and easy to push upstream.

>   * Run IWYU and fix most issues

Is this something that we can try to upstream too? (Does prometheus-cpp already use IWYU?)  I'm wondering if applying IWYU is worth the overhead of making our fork drift more from upstream.

**Comment by silverjam** [comment]
>   * Fix missing std:: on size_t
>   * Fix reference alignment formatting

These also seem like things that we could upstream easily.

**Review by silverjam — APPROVED** [review]
I think we should try to upstream most of these changes and avoid the ones that cause drift from upstream without a large amount of material benefit.  So we could potentially drop IWYU and the clang format changes.

**Comment by silverjam** [comment]
> I think we should try to upstream most of these changes and avoid the ones that cause drift from upstream without a large amount of material benefit. So we could potentially drop IWYU and the clang format changes.
 
Nevermind, looks like prometheus-cpp already uses IWYU so we can submit a PR for that too.  We can probably make a case for the clang-format change too.

**Comment by ljbade** [comment]
@silverjam Good point, I'll drop those minor commits and make PRs for upstream (I'll make a ticket to do this once have bit of time).

The IWYU was originally so that I could make sure the expired metrics stuff had the correct headers, so I'll keep only the stuff directly related to that.

**Comment by ljbade** [comment]
I kept only the expired changes, and rolled one of the `<ctime>` includes IWYU picked up into it. I also rebased again on upstream master as they have fixed the Windows 2016 CI failure.

**Comment by ljbade** [comment]
I opened up some upstream PRs for the smaller changes that I removed from here.
I will now set this to be `master`, and will back up the old fork at `old-master` in case for some reason we still need the old commits.

**Comment by ljbade** [comment]
Master has been updated so closing the PR.

**Pull request merged**
