### PR TITLE
Rename seconds to TTL and use std::chrono

### PR DESCRIPTION
**Pull request by ljbade**
This PR is set to merge on the rebased master, but I will update that once https://github.com/swift-nav/prometheus-cpp/pull/7 is merged.

I found the use of `Seconds()` confusing for the metric expiry time, so I renamed it `TTL()`.

I also updated the expiry code use use `std::chrono` as that is already used in the `Summary` class, and makes the TTL units clearer.

Finally I added a bunch of test cases to check that the expiry stuff is working correctly.

### CODE REVIEW

**Comment by ljbade** [comment]
I will be needing the chrono stuff as well for PR I am currently working on where I need to feed in external time to the summary metric type.

**Review by silverjam — APPROVED** [review]
This look even better for an upstream PR submission, in general we should make reasonable effort to get things upstream so that our forks are as minimal as possible

**Review by notoriaga — APPROVED** [review]

**Comment by ljbade** [comment]
@silverjam yep I think this should be good for upstream. I think replacing steady clock with system clock might be controversial but that was the only way I could then pass in time stamps from recorded data in for replay. I did try to think if there was a way to do make it flexible with templates but ended up a bit of a mess.

**Comment by silverjam** [comment]
> @silverjam yep I think this should be good for upstream. I think replacing steady clock with system clock might be controversial but that was the only way I could then pass in time stamps from recorded data in for replay. I did try to think if there was a way to do make it flexible with templates but ended up a bit of a mess.

Hrmm, OK, maybe we could upstream everything except that change then?

**Comment by ljbade** [comment]
Yeah I think that would make sense. I feel like us replaying data is probably a bit of a corner case for this library...

**Pull request merged**
